/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ru.cardapioru;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author lipe
 */
public class JanelaMostrar extends javax.swing.JFrame {

    /**
     * Creates new form JanelaMostrar
     */
    public JanelaMostrar(InterfacePrincipal interfacePrincipal) {
        initComponents();
        
         areadetexto.setEditable(false);
        for (String cardapio : interfacePrincipal.database) {
                areadetexto.append(cardapio + "\n\n");
        }
        
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areadetexto = new javax.swing.JTextArea();
        BotaoVoltarPrincipal = new javax.swing.JButton();
        TituloRestaurante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 31, 34));

        areadetexto.setEditable(false);
        areadetexto.setColumns(20);
        areadetexto.setLineWrap(true);
        areadetexto.setRows(5);
        areadetexto.setBorder(null);
        areadetexto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        areadetexto.setFocusable(false);
        jScrollPane1.setViewportView(areadetexto);

        BotaoVoltarPrincipal.setBackground(new java.awt.Color(255, 101, 95));
        BotaoVoltarPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        BotaoVoltarPrincipal.setText("Retornar ao menu");
        BotaoVoltarPrincipal.setBorder(null);
        BotaoVoltarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarPrincipalActionPerformed(evt);
            }
        });

        TituloRestaurante.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TituloRestaurante.setText("CARDAPIO SEMANAL - RESTAURANTE UNIVERSITÁRIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotaoVoltarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TituloRestaurante)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(TituloRestaurante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoVoltarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarPrincipalActionPerformed

                    dispose();
    }//GEN-LAST:event_BotaoVoltarPrincipalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoVoltarPrincipal;
    private javax.swing.JLabel TituloRestaurante;
    private javax.swing.JTextArea areadetexto;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
